language: java
env:
  - PLAY_VERSION=1.4.3
  - BUILD_VERSION=1.1
before_script:
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: 
  - play-${PLAY_VERSION}/play auto-test
  - zip -r dcollect-${BUILD_VERSION}.zip optionsplenty/dcollect
  - ls -l dcollect-${BUILD_VERSION}.zip
